services:
  calibre-api:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - calibre-db:/calibre-library:ro
    environment:
      - API_TOKEN=change_this_32_char_token_in_production
    ports:
      - "8000:8000"

volumes:
  calibre-db:
    external: true