services:
  calibre-api:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - calibre-db:/calibre-library:ro
      - cache:/app/cache
    environment:
      - API_TOKEN=change_this_32_char_token_in_production
      - CACHE_TTL_HOURS=4
    ports:
      - "8000:8000"
    depends_on:
      - redis

volumes:
  cache:
  calibre-db:
    external: true